### ISSUE TITLE
User story and test scenarios

### ISSUE THREAD

**Issue by StanimirIliev** [clouway-incubator/scrum_stanimir#1]
# **Goal:**
## We want to implement an financial application <br>in order to report our costs.
---
#  **Description:**
###  The application should have the following features:
*  **Every cost should be described in the nomenclature (fuel, repair, etc) in order to be reported fast and simple, because it could happen in one day to be reported above hundred cost for each employee<br><br>**
* **We should be able to get reference info of costs by days and months for each employee and for the whole company as well**
---
# **Testing scenarios:**    

### Scenario: *Add new cost*  

**<ul>Given that Joe already has unique ID linked with his name, age and other details  
Given that Joe has some cost  
When Joe says, "Register 50$ for fuel with ID-213"  
Then Joe sees that this cost is added successfully to the DB</ul>**

### Scenario: *Get costs for a specific period*  

**<ul>Given that in the database has some registered costs  
When employer says, "I want to see costs from 1st January 2017 to 20th October 2017"  
Then employer sees all costs in this date range</ul>**  

### Scenario: *Get costs for employee for a specific period*  

**<ul>Given that in the database has some registered costs   
When employer says, "I want to see costs of Joe from 1st January 2017 to 20th October 2017"  
Then employer sees all cost in this date range, that Joe is made</ul>**

**Comment by StanimirIliev** [comment]
## When registering new cost, let Joe chose from list of previous used type of costs

**Comment by StanimirIliev** [comment]
### When predefined limit of costs is reached, notify the employer with an e-mail

**Comment by StanimirIliev** [comment]
### When getting the cost, let employer to mark employees in checklist to see only their costs

**Comment by mgenov** [comment]
Every user story should be in separate issue.

**Comment by StanimirIliev** [comment]
Ok, I will change it.

**Comment by StanimirIliev** [comment]
Is this a valid solution for the task?

**Comment by mgenov** [comment]
Each issue should have it's own set of scenarios, so I'm closing this one as it's not related to something concrete. 

Issue = Story Card from the docs.
