### ISSUE TITLE
set optional monthly limit for the costs that each employee could spend

### ISSUE THREAD

**Issue by StanimirIliev** [clouway-incubator/scrum_stanimir#8]

**Comment by mgenov** [comment]
Could you provide some description on this one ? Employees are going to be limited to the number of expenses which they could enter?

**Comment by StanimirIliev** [comment]
When I edit the issues I will open new ones and close these

**Comment by mgenov** [comment]
Why ? You can edit the body of the issue at any time.

**Comment by StanimirIliev** [comment]
I'm closing this issue because has duplicate
